/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FOO_H_RPCGEN
#define _FOO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct autenticacion {
	char *nombreUsuario;
	char *pass;
};
typedef struct autenticacion autenticacion;

struct estadisticas {
	int cantOk;
	int cantUsuarioIncorrecto;
	int cantPassIncorrecta;
	int cantTotal;
};
typedef struct estadisticas estadisticas;

#define UIDPROG 0x20000001
#define UIDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define autenticar 1
extern  int * autenticar_1(autenticacion *, CLIENT *);
extern  int * autenticar_1_svc(autenticacion *, struct svc_req *);
#define getEstadisticas 2
extern  estadisticas * getestadisticas_1(void *, CLIENT *);
extern  estadisticas * getestadisticas_1_svc(void *, struct svc_req *);
extern int uidprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define autenticar 1
extern  int * autenticar_1();
extern  int * autenticar_1_svc();
#define getEstadisticas 2
extern  estadisticas * getestadisticas_1();
extern  estadisticas * getestadisticas_1_svc();
extern int uidprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_autenticacion (XDR *, autenticacion*);
extern  bool_t xdr_estadisticas (XDR *, estadisticas*);

#else /* K&R C */
extern bool_t xdr_autenticacion ();
extern bool_t xdr_estadisticas ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FOO_H_RPCGEN */
