/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "foo.h"


void
uidprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	autenticacion  autenticar_1_arg;
	estadisticas  *result_2;
	char *getestadisticas_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UIDPROG, UIDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	autenticar_1_arg.nombreUsuario="pepito";
	autenticar_1_arg.pass="password";
	
	result_1 = autenticar_1(&autenticar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("autenticar volvio bien\n");
	}
	result_2 = getestadisticas_1((void*)&getestadisticas_1_arg, clnt);
	if (result_2 == (estadisticas *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("estadisticas volvio bien\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	do
	{
		
	}while(false);
	uidprog_1 (host);
exit (0);
}
