/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "foo.h"

int *
autenticar_1_svc(autenticacion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

estadisticas *
getestadisticas_1_svc(void *argp, struct svc_req *rqstp)
{
	static estadisticas  result;

	/*
	 * insert server code here
	 */

	return &result;
}
