/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "foo.h"

bool_t
xdr_autenticacion (XDR *xdrs, autenticacion *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreUsuario, 128))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->pass, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_estadisticas (XDR *xdrs, estadisticas *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cantOk))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantUsuarioIncorrecto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantPassIncorrecta))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantTotal))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->cantOk);
			IXDR_PUT_LONG(buf, objp->cantUsuarioIncorrecto);
			IXDR_PUT_LONG(buf, objp->cantPassIncorrecta);
			IXDR_PUT_LONG(buf, objp->cantTotal);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cantOk))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantUsuarioIncorrecto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantPassIncorrecta))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cantTotal))
				 return FALSE;
		} else {
			objp->cantOk = IXDR_GET_LONG(buf);
			objp->cantUsuarioIncorrecto = IXDR_GET_LONG(buf);
			objp->cantPassIncorrecta = IXDR_GET_LONG(buf);
			objp->cantTotal = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->cantOk))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantUsuarioIncorrecto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantPassIncorrecta))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantTotal))
		 return FALSE;
	return TRUE;
}
