/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "foo.h"


void getEstadisticas_client(char *host)
{
	CLIENT *clnt;
	estadisticas  *result_2;
	char *getestadisticas_1_arg;
#ifndef	DEBUG
	clnt = clnt_create (host, UIDPROG, UIDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_2 = getestadisticas_1((void*)&getestadisticas_1_arg, clnt);
	if (result_2 == (estadisticas *) NULL) {
		printf("REVIENTA\n");
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\n\n\tRESULTADO");
		printf("\n\t------------------------------\n");
		printf("\tCantidad de autenticaciones correctas: %d\n",result_2->cantOk);
		printf("\tCantidad de autenticaciones incorrectas: %d\n",result_2->cantTotal-result_2->cantOk);
		printf("\t\tCantidad de fallos con usuario incorrecto: %d\n",result_2->cantUsuarioIncorrecto);
		printf("\t\tCantidad de fallos con password incorrecta: %d\n",result_2->cantPassIncorrecta);
		printf("\t\tCantidad de fallos inesperados: %d\n",result_2->cantTotal-result_2->cantOk-result_2->cantUsuarioIncorrecto-result_2->cantPassIncorrecta);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void autenticar_client(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	autenticacion  autenticar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UIDPROG, UIDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	autenticar_1_arg.nombreUsuario = malloc(128);
	autenticar_1_arg.pass = malloc(128);	

	printf("\nNombre de usuario: ");
	scanf("%s",autenticar_1_arg.nombreUsuario);
	printf("Password: ");
	scanf("%s",autenticar_1_arg.pass);
	
	result_1 = autenticar_1(&autenticar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\n\n\tRESULTADO");
		printf("\n\t------------------------------\n");
		switch(*result_1)
		{
		case 0:
			printf("\tUsuario y password correctos :-)\n");
			break;
		case 1:
			printf("\tUsuario y/o password incorrectos :-(\n");
			break;
		case 2:
			printf("\tOcurrio un error :-(\n");
			break;
		default:
			printf("\nERROR FATAL");
			exit(0);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int main (int argc, char *argv[])
{
	char *host;
	char choice;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	do
	{
		printf("\n\tMENU");
		printf("\n\t------------------------------");
		printf("\n\n\t 1. AUTENTICAR");
		printf("\n\t 2. ESTADISTICAS");
		printf("\n\t 3. SALIR");
		printf("\n\n Enter Your Choice: ");
		scanf("%c",&choice);
		switch(choice)
		{
		case '1':
			autenticar_client(host);
			break;
		case '2':
			getEstadisticas_client(host);
		    break;
		case '3':
		    exit(0);
		default:
			printf("\nINVALID SELECTION...Please try again");
		}
		getchar();
		printf("\nPresione ENTER para continuar\n");
		getchar();
		//getc();
	}while(1);
	
	return 0;
}
